diagnosisAndStaging <- function(dat) {
  # Returns dat with diagnosis- and staging-related
  # derived variables added

  dat <- within(dat, {

    # From Albert et al. 2011 Table 3
    # In a meeting (I think Feb 23, 2015),
    # Tim said to go with this table rather than
    # the instructions in AJ's email from that morning

    albert.mci.stage <- ifelse(
      is.na(diagnosis.factor) | diagnosis.factor != "MCI", NA,
      ifelse((is.na(amyloidPos) & is.na(tauPos)) | (!is.na(amyloidPos) & !is.na(tauPos) & amyloidPos + tauPos == 1), "Core clinical criteria",
             ifelse((amyloidPos == 1 & is.na(tauPos)) | (is.na(amyloidPos) & tauPos == 1), "due to AD-intermediate likelihood",
                    ifelse(amyloidPos == 1 & tauPos == 1, "due to AD-high likelihood",
                           ifelse(amyloidPos == 0 & tauPos == 0, "unlikely due to AD",
                                  NA)))))

    albert.mci.stage.factor <- factor(albert.mci.stage)

    label(albert.mci.stage) <- label(albert.mci.stage.factor) <- "Albert et al. 2011 MCI categorization"

    # modified version requested in 13 Apr 2015 meeting:
    mod.albert.mci.stage <- ifelse(
      is.na(diagnosis.factor) | diagnosis.factor != "MCI", NA,
      ifelse(!is.na(amyloidPos) & !is.na(tauPos) & amyloidPos + tauPos == 1, 1,
             ifelse((amyloidPos == 1 & is.na(tauPos)) | (is.na(amyloidPos) & tauPos == 1), 2,
                    ifelse(amyloidPos == 1 & tauPos == 1, 3,
                           ifelse(amyloidPos == 0 & tauPos == 0, 0,
                                  NA)))))

    mod.albert.mci.stage.factor <- factor(
      mod.albert.mci.stage,
      levels = 0:3,
      labels = c("unlikely due to AD", "Core clinical criteria", "due to AD-intermediate likelihood", "due to AD-high likelihood"),
      ordered = TRUE
    )

    label(mod.albert.mci.stage) <- label(mod.albert.mci.stage.factor) <- "Modified Albert et al. 2011 MCI categorization"

    # 07 May 2015: I realized that the autogenerated REDCap code
    #  makes this a factor, but not an ordered factor
    mci.stage.factor <- ordered(mci.stage.factor)

  })

  dat
}




